#!/bin/bash

# 🚀 EnergyHub Marketplace Smart Auto-Commit Script
# ==================================================

echo "🚀 EnergyHub Marketplace Smart Auto-Commit"
echo "=========================================="

# Colors for better output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    case $1 in
        "error") echo -e "${RED}❌ $2${NC}" ;;
        "success") echo -e "${GREEN}✅ $2${NC}" ;;
        "warning") echo -e "${YELLOW}⚠️ $2${NC}" ;;
        "info") echo -e "${BLUE}ℹ️ $2${NC}" ;;
        *) echo "📝 $2" ;;
    esac
}

# Get current timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE=$(date '+%Y-%m-%d')

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    print_status "error" "Not in a git repository!"
    exit 1
fi

# Check for changes
if git diff-index --quiet HEAD --; then
    print_status "info" "No changes to commit"
    exit 0
fi

print_status "info" "Detected changes in repository"

# Show git status
echo ""
echo "📊 Current Git Status:"
echo "====================="
git status --short

echo ""
read -p "🤔 Do you want to commit these changes? (y/N): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_status "warning" "Auto-commit cancelled by user"
    exit 0
fi

# Add all changes
print_status "info" "Adding all changes..."
git add .

# Check what's being committed
CHANGED_FILES=$(git diff --cached --name-only | wc -l)
print_status "info" "Ready to commit $CHANGED_FILES file(s)"

# Generate smart commit message based on changed files
COMMIT_MSG="🔄 Auto-commit: Development updates ($DATE)

📊 Summary:
- Files changed: $CHANGED_FILES
- Timestamp: $TIMESTAMP

🔧 Changes include:"

# Analyze changed files and create better commit message
if git diff --cached --name-only | grep -q "README.md"; then
    COMMIT_MSG="$COMMIT_MSG
- 📚 Documentation updates"
fi

if git diff --cached --name-only | grep -q "package.json\|package-lock.json"; then
    COMMIT_MSG="$COMMIT_MSG
- 📦 Dependencies updated"
fi

if git diff --cached --name-only | grep -q "src/"; then
    COMMIT_MSG="$COMMIT_MSG
- 💻 Frontend code changes"
fi

if git diff --cached --name-only | grep -q "backend/"; then
    COMMIT_MSG="$COMMIT_MSG
- 🖥️ Backend API updates"
fi

if git diff --cached --name-only | grep -q "\.css\|\.scss\|tailwind"; then
    COMMIT_MSG="$COMMIT_MSG
- 🎨 Styling improvements"
fi

COMMIT_MSG="$COMMIT_MSG

Generated by smart auto-commit script ⚡"

# Commit changes
print_status "info" "Committing changes..."
if git commit -m "$COMMIT_MSG"; then
    print_status "success" "Commit successful!"
    
    # Push to remote
    print_status "info" "Pushing to remote repository..."
    if git push origin main; then
        print_status "success" "Push successful! Changes are now live."
        print_status "info" "View your repository: https://github.com/SHADRACK152/energyhub_marketplace"
    else
        print_status "error" "Push failed. Please check your connection and try again."
        exit 1
    fi
else
    print_status "error" "Commit failed!"
    exit 1
fi

print_status "success" "Auto-commit completed successfully! 🎉"
