# 🚀 EnergyHub Marketplace Auto-Commit PowerShell Script
# ======================================================

Write-Host "🚀 EnergyHub Marketplace Auto-Commit" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan

# Function to write colored output
function Write-ColorOutput($ForegroundColor) {
    $fc = $host.UI.RawUI.ForegroundColor
    $host.UI.RawUI.ForegroundColor = $ForegroundColor
    if ($args) {
        Write-Output $args
    } else {
        $input | Write-Output
    }
    $host.UI.RawUI.ForegroundColor = $fc
}

# Get current timestamp
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$date = Get-Date -Format "yyyy-MM-dd"

# Check if we're in a git repository
try {
    git rev-parse --git-dir 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-ColorOutput Red "❌ Not in a git repository!"
        exit 1
    }
} catch {
    Write-ColorOutput Red "❌ Git not found or not in a repository!"
    exit 1
}

# Check for changes
$changes = git status --porcelain
if (-not $changes) {
    Write-ColorOutput Green "✅ No changes to commit"
    exit 0
}

Write-ColorOutput Yellow "📊 Found changes in repository"

# Show git status
Write-Host ""
Write-Host "📊 Current Git Status:" -ForegroundColor Blue
Write-Host "=====================" -ForegroundColor Blue
git status --short

Write-Host ""
$response = Read-Host "🤔 Do you want to commit these changes? (y/N)"

if ($response -ne "y" -and $response -ne "Y") {
    Write-ColorOutput Yellow "⚠️ Auto-commit cancelled by user"
    exit 0
}

# Add all changes
Write-ColorOutput Blue "📦 Adding all changes..."
git add .

# Count changed files
$changedFiles = (git diff --cached --name-only | Measure-Object).Count
Write-ColorOutput Blue "ℹ️ Ready to commit $changedFiles file(s)"

# Generate smart commit message
$commitMsg = @"
🔄 Auto-commit: Development updates ($date)

📊 Summary:
- Files changed: $changedFiles
- Timestamp: $timestamp

🔧 Changes include:
"@

# Analyze changed files for better commit message
$cachedFiles = git diff --cached --name-only

if ($cachedFiles -match "README\.md") {
    $commitMsg += "`n- 📚 Documentation updates"
}

if ($cachedFiles -match "package\.json|package-lock\.json") {
    $commitMsg += "`n- 📦 Dependencies updated"
}

if ($cachedFiles -match "src/") {
    $commitMsg += "`n- 💻 Frontend code changes"
}

if ($cachedFiles -match "backend/") {
    $commitMsg += "`n- 🖥️ Backend API updates"
}

if ($cachedFiles -match "\.css|\.scss|tailwind") {
    $commitMsg += "`n- 🎨 Styling improvements"
}

$commitMsg += "`n`nGenerated by PowerShell auto-commit script ⚡"

# Commit changes
Write-ColorOutput Blue "💾 Committing changes..."
git commit -m $commitMsg

if ($LASTEXITCODE -eq 0) {
    Write-ColorOutput Green "✅ Commit successful!"
    
    # Push to remote
    Write-ColorOutput Blue "🚀 Pushing to remote repository..."
    git push origin main
    
    if ($LASTEXITCODE -eq 0) {
        Write-ColorOutput Green "✅ Push successful! Changes are now live."
        Write-ColorOutput Cyan "🌐 View your repository: https://github.com/SHADRACK152/energyhub_marketplace"
    } else {
        Write-ColorOutput Red "❌ Push failed. Please check your connection and try again."
        exit 1
    }
} else {
    Write-ColorOutput Red "❌ Commit failed!"
    exit 1
}

Write-ColorOutput Green "🎉 Auto-commit completed successfully!"
Write-Host ""
Write-Host "Press any key to continue..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
